### PR TITLE
Added Directory for End-to-End Optimization of Scene Layout

### LINKED ISSUE #36: Claim :- End-to-End Optimization of Scene Layout
Paper :- https://arxiv.org/pdf/2007.11744v1.pdf

### PR DESCRIPTION
**Pull request by Bharat-mtr**
This is regarding Issue  #36 
Added Directory on End-to-End Optimization of Scene Layout

Paper :- https://arxiv.org/pdf/2007.11744
Repository:- https://dagshub.com/Bharat-mtr/3D_SLN

Fixes #36

### CODE REVIEW

**Comment by Bharat-mtr** [comment]
@nirbarazida  Please review and let me know if I need to add/edit anything

**Comment by nirbarazida** [comment]
Hey @Bharat-mtr,

Thanks for another great contribution.

As I reviewed the repo on DagsHub, I see that the data directory only holds the metadata about the `SUNCG` dataset and not the dataset itself. As I further investigated, it seems that the dataset is [no longer available](https://github.com/DLR-RM/BlenderProc/issues/11) due to legal issues. As mentioned in the linked issue, it can be replaced with the [3DFront dataset](https://tianchi.aliyun.com/dataset/dataDetail?dataId=65347&lang=en-us), which holds images in the same format but with a different file structure.

Because the 3DFront dataset is under a license that doesn't allow to share it with 3rd parties, I think our best option here is to modify the README file and explain that the `SUNCG` dataset is no longer available, and link to the repo the `3DFront` dataset.

**Comment by Bharat-mtr** [comment]
> Hey @Bharat-mtr,
> 
> Thanks for another great contribution.
> 
> As I reviewed the repo on DagsHub, I see that the data directory only holds the metadata about the `SUNCG` dataset and not the dataset itself. As I further investigated, it seems that the dataset is [no longer available](https://github.com/DLR-RM/BlenderProc/issues/11) due to legal issues. As mentioned in the linked issue, it can be replaced with the [3DFront dataset](https://tianchi.aliyun.com/dataset/dataDetail?dataId=65347&lang=en-us), which holds images in the same format but with a different file structure.
> 
> Because the 3DFront dataset is under a license that doesn't allow to share it with 3rd parties, I think our best option here is to modify the README file and explain that the `SUNCG` dataset is no longer available, and link to the repo the `3DFront` dataset.

Thanks for pointing out.
I have updated the README accordingly.
Please review it.

Thanks.

**Comment by Bharat-mtr** [comment]
i have made the required changes @nirbarazida @deanp70 , please review it & merge it

**Review by deanp70 — APPROVED** [review]

**Comment by deanp70** [comment]
Thanks for the contribution @Bharat-mtr!

**Pull request merged**
