### PR TITLE
Added Directory for Neural Rays for Occlusion-aware Image-based Rendering

### LINKED ISSUE #37: Claim :- Neural Rays for Occlusion-aware Image-based Rendering
Paper:- https://arxiv.org/pdf/2107.13421

### PR DESCRIPTION
**Pull request by Bharat-mtr**
This is regarding Issue  #37 
Added Directory on Neural Rays for Occlusion-aware Image-based Rendering

Paper :- https://arxiv.org/pdf/2107.13421.pdf
Repository:- https://dagshub.com/Bharat-mtr/NeuRay

Fixes #37

### CODE REVIEW

**Comment by Bharat-mtr** [comment]
@nirbarazida  Please review and let me know if I need to add/edit anything.

**Comment by nirbarazida** [comment]
Hey @Bharat-mtr,

Thanks for your contribution to our challenge!

I had only one small comment for this PR. please review it, make the changes and we'd love to merge it!

**Comment by Bharat-mtr** [comment]
> Hey @Bharat-mtr,
> 
> Thanks for your contribution to our challenge!
> 
> I had only one small comment for this PR. please review it, make the changes and we'd love to merge it!

Hi @nirbarazida ,

Thanks for reviewing. Please let me know what i need to change/add to this PR. I can't see where you added the comment about this PR.

Thanks.

**Comment by nirbarazida** [comment]
Hey @Bharat-mtr ,

My comment is on lines 35-37 where you refer to a different platform to download the model and dataset, which is missing the point of the challenge. Please modify it and instruct how to use DagsHub & DVC to pull them.

**Comment by Bharat-mtr** [comment]
> Hey @Bharat-mtr ,
> 
> My comment is on lines 35-37 where you refer to a different platform to download the model and dataset, which is missing the point of the challenge. Please modify it and instruct how to use DagsHub & DVC to pull them.

I have updated the README as you said.
Please review it and let me know if I need to add/edit anything.
Thanks!

**Comment by Bharat-mtr** [comment]
I have made the required changes, please review it @nirbarazida @deanp70  and merge it.

**Review by deanp70 — APPROVED** [review]

**Comment by deanp70** [comment]
Thank you for your contribution! I've merged this in! Nice job

**Pull request merged**
